// BodyBox.jsx
// import React from 'react'

export const BodyBox = () => {
  return (
    <>
    <div>BodyBox1</div>
    <div>BodyBox2</div>
    <div>BodyBox3</div>
    <div>BodyBox4</div>
    <div>BodyBox5</div>
    <div>BodyBox6</div>
    <div>BodyBox7</div>
    <div>BodyBox8</div>
    <div>BodyBox9</div>
    <div>BodyBox10</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    <div>BodyBox</div>
    </>

  )
}
